name: manual trigger
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'enter env key'
        required: true
        default: 'staging'
      tags:
        description: 'nter tags'
        required: false
        default: boolean
jobs:
  my-manual-trig-job:
    runs-on: ubuntu-latest
    steps:
      - name: say Hi
        run: echo "Hi..."
