name: static matrix demo
on:
  workflow_dispatch:
jobs:
  build:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
      node: [18,20,22]
    fast-fail: false
    name: Build ${{ matrix.os}}, Node ${{ matrix.node}}
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
    - name: print info
      run: |
        echo "running on ${{matrix.os}} and node has  ${{matrix.node}}"
        node -v
        npm -v
    - name: run test
      run: npm test



