name: Runner Test
on: workflow_dispatch

jobs:
  hello:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from self-hosted runner!"
